ansible_host: 10.0.3.208 
ansible_ssh_private_key_file: /var/jenkins_home/.ssh/us-east-1key.pem 
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q ec2-user@bastion"'

